version: "3.9"
services:
  db:
    image: kurthunter/sqlserver:v2
    container_name: sqlserver-db
    restart: always
    environment:
      SA_PASSWORD: YourStrong!Passw0rd
      ACCEPT_EULA: "Y"
    volumes:
      - dbdata:/var/opt/mssql
    networks:
      - backend
  web:
    image: tp3
    container_name: tp3-web
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=AppCustomerDiiageDbe;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    networks:
      - backend

volumes:
  dbdata:

networks:
  backend:
    driver: bridge