name: Build and Push Docker image

on:
  push:
    branches: [ main ]

jobs:
  build-test-push:
    runs-on: self-hosted # ou 'ubuntu-latest' si tu n'utilises pas de runner local
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t docker.io/ttmartinksdocket/tp3-web:latest .

      - name: Test Docker image
        run: docker run --rm docker.io/ttmartinksdocket/tp3-web:latest dotnet --info

      - name: Login to Docker Hub
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login docker.io -u "${{ secrets.REGISTRY_USER }}" --password-stdin

      - name: Push Docker image
        run: docker push docker.io/ttmartinksdocket/tp3-web:latest
